### ISSUE TITLE
[Security Issue] - Malicious game contract can drain all the funds from the contract And prevent users from withdrawing their funds

### ISSUE THREAD

**Issue by OceansAndThunders** [YOLOrekt/community-bug-bounty#5]
Hello team,

If an admin creates a game contract address, then this contract owner later can abuse the "gameUpdateUserBalance" function,
the "gameUpdateUserBalance" updates the given user address balance on the Yolo Wallet, doing so the malicious game contract do the following steps
- User A,B,C deposits some amount of money to YoloWallet (lets say total 300ETH)
- Now the "stablecoinTokenContract" will forwards 300 ETH from these users to this contract (address(this))
- Malicious game contract trigger the "gameUpdateUserBalance" function with his address and specific amount (let's say 300 (as 300ETH))
- Now malicious game contract triggers the "withdraw" function with his very huge amount of tokens (which will bypass : amount <= balances[sender])
- this will transfers the worth of 300 ETH from the "stablecoinTokenContract" from "address(this)" to the malicious caller
- And leave the contract drained of all funds

The same scenario can happens by using the "gameReduceUserBalance" and make users permanently lose their funds (they won't be able to withdraw them anymore)

FIX:
Use a further check given by contract governance or owner, example :

```
// use this to define the permitted amount to be gained/reduced by a specific game contract 
...
mapping(address=>uint256) public allowedAmount;
...

// Function to set the permitted amount (only called by admins)

function updatePermittedAmount(address _gameContract,uint256 amount) onlyAuthorized(ADMIN_ROLE) {
    
    allowedAmount[address(_gameContract)] = amount;
}
function gameUpdateUserBalance(address user, uint256 amount)
        external
        onlyGameContract
    {
        // Now check this amount is permitted or not
        require(amount<allowedAmount[address(msg.sender)],"you're not allowed to gain this amount");
       // Update the permitted amount
        allowedAmount[address(msg.sender)] -= amount;
        balances[user] += amount;
    }
```

**Comment by CryptoKiddies** [comment]
This submission is related to an out of scope issue. If you check [QuillHash Audit section D3](https://s3.amazonaws.com/audit-report.yolorekt.finance/YoloRekt+Smart+Contract+Final+Audit+Report_072622.pdf), we have acknowledged the potential for abuse. We are a chiefly US-based public team and will not rug our users as that will destroy the reputation of our company, team members, any future tokens, and open us up to liability. We appreciate the diligence, but because of the aforementioned, it not eligible for a reward.
